### ISSUE TITLE
Wild Idea: Is it possible to make it work on Google Colab?

### ISSUE THREAD

**Issue by amrrs** [Sangarshanan/jazzit#11]
I'm not sure if it's possible given that it's a remote machine and a web browser, but maybe some HTML player like thing can help? 

Not really an ask, more like an idea

**Comment by tas09009** [comment]
I was able to play a song on Jupyter Notebook. Let me see if I can try it with Colab

**Comment by amrrs** [comment]
@tas09009 Tried didn't seem to work. 
`from IPython.display import Audio` This seems to be the way but I'm not sure if it could be autoplayed and stopped

**Comment by amrrs** [comment]
Autoplay is just another argument 😣https://stackoverflow.com/a/20806969/5086335

**Comment by Sangarshanan** [comment]
Music on-error seems fairly easy to implement `Ipython Audio`

Working on figuring out how to run this properly as a daemon process to use it in long-running scripts
came up with a very rough kinda working code (not the best way to do this) will try to hack something around this

```python
import time  
import IPython.display as ipd
from multiprocessing import Process

def remind_me(seconds):
    while True:
        print("Starting Music")
        ipd.display(ipd.Audio("https://www.myinstants.com/media/sounds/musique-dascenseur-mp3cut.mp3", autoplay=True))
        time.sleep(10)

def background_music():
    process = Process(target=remind_me, name="Reminder", args=(1,))
    process.start()
    for _ in range(0,20):
        print("Running...")
        time.sleep(1)
    process.terminate()
    process.join()

background_music()
```

**Comment by Sangarshanan** [comment]
Running on colab https://colab.research.google.com/github/Sangarshanan/jazzit/blob/master/notebook.ipynb : )

Closing this with #18
