### ISSUE TITLE
It does not play any track at all

### ISSUE THREAD

**Issue by Amazeryogo** [Sangarshanan/jazzit#12]
So I downloaded this library and tried out the example on the README.md

`from jazzit import error_track

@error_track('elevator.mp3', wait=7)
def run():
    for num in reversed(range(10)):
        print(10/num)

if __name__ == "__main__":
    run()`

but when I run this, I don't hear any sound but instead, I get this output:

Traceback (most recent call last):
  File "/home/me/.local/lib/python3.8/site-packages/jazzit/jazz.py", line 61, in wrapped_function
    original_func(*args)
  File "jazz.py", line 6, in run
    print(10/num)
ZeroDivisionError: division by zero
/bin/sh: 1: python: not found

**Comment by Sangarshanan** [comment]
Could you share the output of `which python` ?
From the looks for it seems to be the same as  #8

**Comment by Sangarshanan** [comment]
This should be solved by #14
