### ISSUE TITLE
Add ipython support 

### ISSUE THREAD

**Issue by Sangarshanan** [Sangarshanan/jazzit#18]
ref #11 

Add Support for Jazzit to work on collab/ Jupyter notebooks natively with Audio tag 

Maybe support ipython magic along with decorator

**Comment by amrrs** [comment]
On Local Jupyter it's working without the Audio tag!

**Comment by Sangarshanan** [comment]
I also wanted to get rid of `Pygobject` with the audio tag usage on notebooks will be OS agnostic

**Comment by Sangarshanan** [comment]
also added ipython `magic` along with the decorator, so execution is not dependent on the code being wrapped in a function

**Comment by amrrs** [comment]
Wow that's nice. That's some dedication to open source development ! Kudos 👏🏽!
