### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by AdeelK93** [Sangarshanan/jazzit#7]
I'm hardly a python expert, but I believe this library doesn't work with Windows. Below is the error I'm getting.

AttributeError: module 'os' has no attribute 'setsid'

**Comment by Sangarshanan** [comment]
Ah yes `setsid` is only supported on Unix, Will have to fix it 
Thanks for bringing this up : )

ref: https://stackoverflow.com/questions/38083168/attributeerror-module-os-has-no-attribute-setsid

**Comment by fekga** [comment]
This one might be good for killing the process:
https://stackoverflow.com/a/52921766/6464041

**Comment by Sangarshanan** [comment]
Fixed with #14 : )
